project_id = "eliropadiywofniisknp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.list-users]
    verify_jwt = false
  [functions.promote-first-admin]
    verify_jwt = false
  [functions.toggle-provvigioni]
    verify_jwt = false
