
CREATE TABLE public.clienti_anagrafica (
  nome_cliente text PRIMARY KEY,
  indirizzo text,
  provincia text
);

ALTER TABLE public.clienti_anagrafica ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read anagrafica"
  ON public.clienti_anagrafica
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage anagrafica"
  ON public.clienti_anagrafica
  FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

INSERT INTO public.clienti_anagrafica (nome_cliente, indirizzo, provincia) VALUES
('A.I.M.E. SRL', 'Via Gabriele D''Annunzio 336', 'MO'),
('A.P.S. DUE SRL', 'Via Giuseppe Fuca'' 156, Modena', 'MO'),
('ALISEO SRL', 'Via Abramo Lincoln 11/B, Carpi', 'MO'),
('ALTALUCE SRL', 'Via Madrid 12/4, Sassuolo', 'MO'),
('AMADEI AURO S.R.L.', 'Via Renato Prati 54, Modena', 'MO'),
('ARCHIMEDE PLUS S.N.C. DI', 'Via Mar Tirreno 260, Modena', 'MO'),
('ARTECASA SRLS', 'Via Fratelli Cairoli 8, Casalecchio di Reno', 'BO'),
('ASSISTEC SRL', 'Via De'' Gavasseti 312, Modena', 'MO'),
('AUGUSTA S.R.L.', NULL, NULL),
('AURA IMPIANTI S.R.L.', 'Via Leoni Giovanni e Lodovico 4, Modena', 'MO'),
('AUTEL S.R.L', 'Via Bagnoli 9, Sassuolo', 'MO'),
('B. & B. DENTAL S.R.L.', 'Via San Benedetto 1837, San Pietro in Casale', 'BO'),
('BASCHIERI S.R.L.', 'Via Oslo 26, Sassuolo', 'MO'),
('BCG TECHNOLOGY S.R.L.', 'Via Ferrara 17, San Pietro in Casale', 'BO'),
('BORSARI LUCIANO SRL', 'Via Papa Giovanni XXIII 22, Modena', 'MO'),
('BORTOLINI P.I CLAUDIO', NULL, NULL),
('C.B. TECNOIMPIANTI SRL', 'Via Paraviana 179, Vignola', 'MO'),
('C.F.IMPIANTI ELETTRICI DI CAMM', NULL, NULL),
('CANTORE IMPIANTI', 'Via Martinelli 21', 'MO'),
('CANTORE IMPIANTI S.R.L.', 'Via Mar Mediterraneo 20, Modena (MO)', 'MO'),
('CAPELLINI IMPIANTI ELETTRICI', NULL, NULL),
('CARBONI SERGIO', NULL, NULL),
('CARINI DAVIDE E C. SNC', 'Via Poggi 8/A, Valsamoggia (BO)', 'BO'),
('CASELLI GIAN LUCA', NULL, NULL),
('CASSANELLI DI CASSANELLI', 'Via Val di Sasso 45/47', 'MO'),
('CEIEB SRL', 'Via Albert Einstein 3, Valsamoggia', 'BO'),
('CONEXIA SRL', 'Via Germania 29/31, Carpi', 'MO'),
('CONTRI DAMIANO', NULL, NULL),
('CROVETTI MARIO', 'Piazza S. Andrea 15, Pievepelago (MO)', 'MO'),
('D-TECH S.R.L.', 'Via Perosi 6, Modena', 'MO'),
('DIMA S.R.L.', 'Via Leonardo Sciascia 60, Modena', 'MO'),
('DOT SRL', NULL, NULL),
('E.B.M SRL', 'Viale San Martino 48/B, Sassuolo', 'MO'),
('E.T.S. SRL SEMPLIFICATA', 'Via Cassola di Sotto 42/E', 'MO'),
('EFFE-GI IMPIANTI S.R.L.', 'Via della Repubblica 2030/ABC, Vergato', 'BO'),
('EFFETTO QUADRO S.R.L.', NULL, NULL),
('ELECTRIC CP SRL', 'Via Castelfranco 17/B, Valsamoggia', 'BO'),
('ELECTRIC START SRL', 'Via Gioacchino Rossini 7, Castelvetro di Modena', 'MO'),
('ELETTRA 2 ELLE S.R.L.', 'Via Solferino 10, Fiorano Modenese', 'MO'),
('ELETTRIC SYSTEM SRL', 'Via Austria 26', 'MO'),
('ELETTRICA 2000 SRL', 'Via Monte Grappa 25', 'MB'),
('ELETTRICA 77 AUTOMATION SRL', 'Via Renato Guttuso 2/A, Scandiano', 'RE'),
('ELETTRO 2000 DI DEBBIA WILLIAM', 'Via Giovanni Fattori 14, Scandiano', 'RE'),
('ELETTRO 2000 SNC', 'Via Volturno 90, Cavezzo', 'MO'),
('ELETTRO 93 DI MORETTI SANDRO', 'Via dei Liutai 14, Castelfranco Emilia', 'MO'),
('ELETTRO-IN SRL', 'Via F. Malavolti 9, Modena', 'MO'),
('ELETTROART 2 S.R.L.', 'Via della Resistenza 12, Ventasso', 'RE'),
('ELETTROMILK SRL', 'Via Giuseppe Di Vittorio 11, Pavullo nel Frignano', 'MO'),
('ELETTRONE DI SAVINI SIMONE', NULL, NULL),
('ELETTROSERVICE DI PRETI', NULL, NULL),
('ELETTROTECH DI', NULL, NULL),
('ELETTROTECNICA ELLEEFFE SRL', 'Via W. Tabacchi 33, Bomporto', 'MO'),
('ELLE 4 SRL', 'Via Fratelli Cervi 60, Vignola', 'MO'),
('ELLE-DI-BI SNC STRUZZI PIETRO', NULL, NULL),
('ELWATT SRL', 'Via Aristotele 22, Reggio nell''Emilia', 'RE'),
('ERREVI CERAMICS S.R.L.', 'Via Giovanna Maria Dallari 2, Sassuolo', 'MO'),
('ESSE DUE IMPIANTI SNC', 'Via Per Panzano 41', 'MO'),
('ESSETIEFFE IMPIANTI', 'Via Athos Jori 96', 'MO'),
('EUROELETTRA S.R.L.', 'Via Umberto Cantù 1, Reggio Emilia (RE)', 'RE'),
('EUROLAM S.R.L.', 'Via G. Marconi 350, Serramazzoni', 'MO'),
('F.G.F. IMPIANTI SRL', 'Strada Statale 467 85, Casalgrande', 'RE'),
('F.M.IMPIANTI', NULL, NULL),
('FABBRI-IMPIANTI S.R.L. SEMPLIF', 'Via Adda 51, Sassuolo', 'MO'),
('FERRAMENTA BONACORSI', 'Via dell''Industria 2, Sestola', 'MO'),
('FERRAMENTA VANDELLI MAURIZIO', 'Via Regina Pacis 38, Sassuolo', 'MO'),
('FINI STEFANO DI FINI OLINTO', 'Via Dell''Artigianato 10, Serramazzoni (MO)', 'MO'),
('FIORI VIVIANO SRL', 'Via della Repubblica 842/A, Vergato', 'BO'),
('FONDAROLI DAVIDE', NULL, NULL),
('FONDAROLI ENNIO', NULL, NULL),
('FONTANA PIETRO E C. SNC', 'Via Ascari 14, Maranello', 'MO'),
('FR IMPIANTI ELETTRICI S.R.L.', 'Via del Tiglio 26, Carpi', 'MO'),
('G.ELETTRICA SNC', NULL, NULL),
('G.L. IMPIANTI S.R.L.', 'Via Cicogna 99', 'BO'),
('G.P.E. IMPIANTI SRL', 'Via Vittorio Bachelet 50', 'MO'),
('GAGGIA S.P.A.', 'Via Torretta 240, Gaggio Montano', 'BO'),
('GALLI MAURIZIO', 'Via Pier Paolo Molinelli 9, 40141 Bologna (BO)', 'BO'),
('GAPE DUE SPA', 'Viale Regina Pacis 306, Sassuolo', 'MO'),
('GETRA DI GENNARI SIMONE', 'Via Gatta 10', 'RE'),
('GIOVANARDI S.R.L.', 'Viale Magenta 16-18-20, Sassuolo', 'MO'),
('GIOVANELLI IMPIANTI SRL', 'Via Panaro 88, Savignano sul Panaro', 'MO'),
('GIUGNI SRL', 'Via Felice Bellotti 53', 'MO'),
('GRANITIFIANDRE SPA', 'Via Radici Nord 112, Castellarano', 'RE'),
('GRUPPO SIRIO SRL', 'Via Vincenzo Monti 108', 'MO'),
('HOME IMPIANTI SNC', NULL, NULL),
('IMMOVILLI IMPIANTI SRL', 'Via Paolo Monelli 122', 'MO'),
('IMPIANTI ACQUALUCE SNC DI LAMI', 'Via Don L. Lenzini 1', 'MO'),
('IMPRESA BACCHELLI SRL', 'Viale Ciro Menotti 43', 'MO'),
('ING.FERRARI SPA', 'Via Mons. Giuseppe Pistoni 40, Modena', 'MO'),
('IPM SRL', 'Via di Vittorio 2', 'MO'),
('ISR SRL', 'Via Della Meccanica 26, San Cesario sul Panaro (MO)', 'MO'),
('ITALTRACTOR ITM S.P.A.', 'Via Confortino 30, Valsamoggia', 'BO'),
('IVCAR SNC DI MAZZETTI', 'Piazza IV Novembre 13', 'MO'),
('IZETA DI BORTOLOTTI STEFANO', NULL, NULL),
('JOULE TECHNOLOGY SRL', 'Via Emilia all''Ospizio 12', 'RE'),
('KDS IMPIANTI S.R.L.', 'Via Alcide De Gasperi 16', 'MO'),
('KEVAC SRL', 'Via Trilussa 1', 'BO'),
('LAMANDINI IMPIANTI SNC', 'Via Castelfranco 17/F', 'BO'),
('LAMINAM SPA', 'Via Ghiarola Nuova 258, Fiorano Modenese', 'MO'),
('LEAR ENGINEERING S.R.L.', 'Via Grecia 45/47', 'MO'),
('LIGUORI IMPIANTI S.R.L.', 'Via del Litografo 1', 'BO'),
('LOMBARDI GESTIONI S.R.L.', 'Via dell''Industria 5', 'MO'),
('LP IMPIANTI DI LUCCHINI PIERO', 'Via Sillaro 2800/A', 'BO'),
('M.B. FERRARI S.R.L.', 'Via Limana 125', 'MO'),
('M2 IMPIANTI ELETTRICI', NULL, NULL),
('MAGAGNOLI IMPIANTI DI', NULL, NULL),
('MALFERRARI SRL', 'Via P. Tarozzi 31-33-35, Castelfranco Emilia (MO)', 'MO'),
('MANZOLI SIMONE', NULL, NULL),
('MARTI SISTEMI DI MARCO INCERTI', 'Via B. Marcello 26/A, 41122 Modena', 'MO'),
('MASINELLI MASSIMO', NULL, NULL),
('MATTEO CALZOLARI', 'Via Grizzaga 96, Maranello (MO)', 'MO'),
('MEBER SRL', 'Viale Artigianato 1, 41012 Carpi', 'MO'),
('MONTEBELVEDERE TERMOIDRAULICA', 'Via Montebelvedere 3032, Montese (MO)', 'MO'),
('MORDINI CORRADO SNC', 'Via Roma 153, 41027 Pievepelago', 'MO'),
('MORDINI PIETRO', NULL, NULL),
('MULTIPACK SRL', 'Via Domenico Cimarosa 5, Casalecchio di Reno', 'BO'),
('NEOTEKNA SRL', 'Via Quattro Passi 100, 41043 Formigine', 'MO'),
('NEW LIGHT SRL', NULL, NULL),
('NEW TRADE SRL', NULL, NULL),
('NIAM SRL', 'Via Maestri Del Lavoro 30, 41037 Mirandola', 'MO'),
('NORTON SRL', 'Via Vignola 48, 41053 Maranello', 'MO'),
('O.B.M IMPIANTI SRL', 'Via degli Artigiani 12, 41036 Medolla', 'MO'),
('OFFICINE SMAC S.P.A.', 'Via Sacco e Vanzetti 13/15, Fiorano Modenese', 'MO'),
('OLIVERIO S.R.L.', 'Via Vinca 12, San Giorgio di Piano (BO)', 'BO'),
('PANDEMONIUM SRL SEMPLIFICATA', 'Via Poggiobianco 604, 41055 Montese (MO)', 'MO'),
('PATTAROZZI - BONCOMPAGNI SRL', 'Via Nicola Campanile 6, 41026 Pavullo nel Frignano', 'MO'),
('PATTAROZZI GUALTIERO', NULL, NULL),
('PHARMADESIGN S.R.L.', NULL, NULL),
('PIANELLI PIERLUIGI', 'Via Casa Zorra 1960, Fanano (MO)', 'MO'),
('PIETRO FIORENTINI S.P.A.', 'Via Enrico Fermi 8/10, Arcugnano', 'VI'),
('PILATI DANTE DI PILATI CARLO', 'Via Petrarca 61, Castelfranco Emilia (MO)', 'MO'),
('PORCELAINGRES GmbH', 'Via Radici Nord 112, Castellarano (RE)', 'RE'),
('PRO ENERGY GROUP SRL', 'Via Giardini Nord 75, 41026 Pavullo nel Frignano', 'MO'),
('PROJECTA ENGINEERING SRL', 'Via Viazza 2 Tronco 55, 41042 Fiorano Modenese', 'MO'),
('PS IMPIANTI', 'Via Fondovalle Trentino 1787/A, Fanano (MO)', 'MO'),
('R.W DI RIGHI WILLIAM', NULL, NULL),
('RAM ELETTRONICA SPA', 'Via della Meccanica 9/11, San Cesario sul Panaro', 'MO'),
('RICHELDI IMPIANTI SRL', 'Via Selva 646, 41028 Serramazzoni', 'MO'),
('ROSSI ELETTRONICA IMPIANTI SRL', 'Via Cicogna 71, 40068 San Lazzaro di Savena', 'BO'),
('ROSSI ELETTRONICA SRL', 'Via Montegrappa 28, Solignano di Castelvetro (MO)', 'MO'),
('ROSSI MASSIMO', 'Via Irma Marchiani 34, 41026 Pavullo nel Frignano', 'MO'),
('ROVINALTI SRL', 'Via Giardini Nord 113, Pavullo nel Frignano (MO)', 'MO'),
('S.D.M. AUTOMAZIONI S.R.L.', 'Via Giuseppe Garibaldi 41', 'MO'),
('SACMI TECH S.P.A.', 'Via Provinciale Selice 17/A, Imola', 'BO'),
('SAIEM SRL', 'Via del Crociale 56', 'MO'),
('SERVIZI GLOBALI CASA S.R.L.', 'Via Labriola 22/C', 'MO'),
('SIA DI IRDI SHPATA', NULL, NULL),
('SICEL S.R.L', 'Via della Chimica 4', 'MO'),
('SINERGICA IMPIANTI SRL', 'Via Paraviana 350', 'MO'),
('SNOW SERVICE SRL', 'Via dell''Industria 34', 'MO'),
('SYSTEM CERAMICS S.P.A.', 'Via Ghiarola Vecchia 73, Fiorano Modenese', 'MO'),
('SYSTEM ENGINEERING &', 'Via Adua 102/A', 'RE'),
('SYSTEM SICUREZZA S.R.L.', 'Via Ghiarola Vecchia 73', 'MO'),
('T.E.M.A SPA', 'Via della Scienza 21/A, Castelnuovo Rangone', 'MO'),
('TC IMPIANTI S.R.L.', 'Via Casino Levizzano 6, Baiso (RE)', 'RE'),
('TECNO-EXPRESS', 'Via Piero Gobetti 156', 'MO'),
('TECNO-STAR DUE SRL', 'Via dei Marmorari 88', 'MO'),
('TECNO5 IMPIANTI TECNICI SRL', 'Via Emilia Ovest 101, Modena (MO)', 'MO'),
('TECNOCLIMA SRL', 'Via Fratelli Rosselli 29', 'MO'),
('TM SOCIETA'' A RESPONSABILITA''', NULL, NULL),
('TONELLI IMPIANTI SOCIETA'' A RE', NULL, NULL),
('TOP LEVEL DI STRUZZI SERGIO', 'Via Cella Di Sotto 40, Fanano', 'MO'),
('TRENTI FRANCO SRL', 'Via Matilde di Canossa 1', 'BO'),
('TURCHI CHRISTIAN', 'Via Pigna 10, Fanano (MO)', 'MO'),
('TUSCANIA SPA', 'Via Giardini Sud 4603, Serramazzoni', 'MO'),
('UNIIMPIANTI SRL', 'Via Costa 10/A, Nonantola (MO)', 'MO'),
('VELA SRL', 'Via M. D''Azeglio 36-38, Novellara (RE)', 'RE'),
('VER TOP S.R.L.', 'Via Statale Est 48, Fiorano Modenese (MO)', 'MO'),
('VERRONE MARCO', NULL, NULL),
('VERUCCHI IMPIANTI S.R.L.', NULL, NULL),
('VIGNOL SYSTEM SRL SOCIO UNICO', 'Via Foschiero 1623, Spilamberto (MO)', 'MO'),
('VILE VINILE', 'Via Giardini Nord 103, Serramazzoni (MO)', 'MO'),
('VILLA TORRE S.R.L.', NULL, NULL),
('WILDE IMPIANTI ELETTRICI DI', NULL, NULL);
